name: Build (Android)

on: [push, pull_request]

jobs:
  android:
    name: ${{ matrix.platform.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: nttld/setup-ndk@v1
        id: setup_ndk
        with:
          ndk-version: r21e
      - name: Build (Android.mk)
        run: |
          ./build-scripts/androidbuildlibs.sh
      - name: Check artifacts
        uses: andstor/file-existence-action@v1
        with:
          files: "build/android/lib/x86_64/libSDL2.so"
          allow_failure: true
      - name: Gather artifacts
        run: |
          mkdir artifacts
          mkdir artifacts/x64
          mkdir artifacts/arm64
          cp "build/android/lib/x86_64/libSDL2.so" "artifacts/x64/libSDL2.so"
          cp "build/android/lib/arm64-v8a/libSDL2.so" "artifacts/arm64/libSDL2.so"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sdl2-android
          path: artifacts/
          retention-days: ${{ (github.event_name == 'pull_request' || github.ref_name != 'master') && 7 || 90 }}
